### ISSUE TITLE
Error building to Android

### ISSUE THREAD

**Issue by catmq** [Swrve/swrve-unity-sdk#141]
Unity 5.5.2 on both Mac and Windows, Tested with Samsung Galaxy S7 and S7 edge, both have Android 6.0.1

The process:
1) New project
2) import Swrve unity sdk 4.9.1 using .unitypackage, open up Scene DemoScene5x
3) enter AppID and Api Key to Swrve prefab
4) Switch platform to Android
5) play mode in Unity works well
6) Try make a build to Android and failed

     Error Message:
<img width="794" alt="screen shot 2017-05-01 at 14 14 39" src="https://cloud.githubusercontent.com/assets/4716963/25595376/720e0698-2e79-11e7-9e93-5113a43ec2b2.png">
<img width="789" alt="screen shot 2017-05-01 at 14 21 43" src="https://cloud.githubusercontent.com/assets/4716963/25595401/8f05e57c-2e79-11e7-8cd4-26b3ad9a49ad.png">
<img width="790" alt="screen shot 2017-05-01 at 14 21 56" src="https://cloud.githubusercontent.com/assets/4716963/25595407/90e5e360-2e79-11e7-8bc2-d45b25564c9d.png">

I am not very familiar with Android native development so I am not sure if it is a bug or I missed a setting somewhere. Hope someone can help!

**Comment by davidbreenwex** [comment]
Hi catmq,

Unity doesn’t support modern features from Android, such as the use of ${applicationId} in AndroidManifest.xml files. 

Due to this, you must run SwrveBuildComponent.AndroidPrebuild(), which replaces ${applicationId} with your project’s bundle ID. 
If you’re running continuous integration (CI) builds, it’s best to call this before every Android build.

There is also a helper menu item to do this: Swrve -> Android Prebuild in AndroidManifests. (see screenshot1 attached).

Can you try running this before making an Android build?
![screenshot1](https://cloud.githubusercontent.com/assets/7482529/25598071/91906db8-2e87-11e7-9ba7-b781792f3258.png)

**Comment by catmq** [comment]
Thanks so much for the quick reply! 

After I did the prebuild, it could build without a problem, but the app would crash as soon as I launch it. logcat gives the following message:

<img width="1075" alt="screen shot 2017-05-01 at 16 44 01" src="https://cloud.githubusercontent.com/assets/4716963/25598985/6e491a52-2e8d-11e7-9058-b5078642fcca.png">

Any idea why this might happen?

**Comment by Sergio-Mira** [comment]
HI @catmq, the JNI error suggest it has something to do with the communication with the Java native code. Do you have the .jar and .aar files? Could you attach a full log of the startup of the game?

**Comment by catmq** [comment]
Hi @Sergio-Mira 
For .jar and .aar I just used the ones included in the 4.9.1 release
https://github.com/Swrve/swrve-unity-sdk/releases
Here is a screenshot of the Unity Plugin/Android folder:
<img width="296" alt="screen shot 2017-05-03 at 14 03 56" src="https://cloud.githubusercontent.com/assets/4716963/25681512/61e1f784-3009-11e7-8fc2-5d584c601198.png">
I basically just import the .unitypackage into an empty Unity project and did nothing else.

So I did another build in development mode and now it is given a different error message
<img width="872" alt="screen shot 2017-05-03 at 14 12 36" src="https://cloud.githubusercontent.com/assets/4716963/25681846/b469ea42-300a-11e7-9d70-a8346b0ae0c0.png">

Attached the full log when the app starts up:
[SwrveTest_logcat.txt](https://github.com/Swrve/swrve-unity-sdk/files/974713/SwrveTest_logcat.txt)

Any help is appreciated!
Thanks so much!

**Comment by Sergio-Mira** [comment]
Hi @catmq I have the same issue here with latest Unity and our latest SDK in an empty project. I've pinpointed it to 'IsSupportedAndroidVersion' which for some reason cannot find the native class 'com.swrve.sdk.SwrveUnityCommon' although it is in the final apk. I'll have more information soon.

**Comment by Sergio-Mira** [comment]
Looks like JNI calls can fail if called from the class constructor. I have a hotfix in the pipeline and will be releasing it soon.

**Comment by Sergio-Mira** [comment]
@catmq could you give the 4.9.2 hotfix a go? https://github.com/Swrve/swrve-unity-sdk/releases/tag/4.9.2
Thanks!

**Comment by catmq** [comment]
Just got to test it and it works! Thanks so much!

There is only a little problem with 4.9.2. In 4.9.2 the default value for Events and Contents server is using http instead of https, so when I initially created a new project with 4.9.2, I kept getting an error that says "App ID In URL Must Match API Key". It took me a while to figure out what the problem is.

Anyway, thanks so much for the help!

**Comment by Sergio-Mira** [comment]
Glad to hear it worked!
If you leave the Event and Content endpoints empty they will be generated at runtime (there is also a flag in the Config object to control HTTP/HTTPS and HTTPS is enabled by default). We want to improve the setup in a major version to avoid this problems.

I'll close this issue but let us know if you have any other feedback. Thanks again!
