### ISSUE TITLE
Problems with accessing internal variables in SwrveButtonTriggerEvent.cs

### ISSUE THREAD

**Issue by aaslun** [Swrve/swrve-unity-sdk#142]
Hi!

We updated Unity to version 2017.1.1 and installed Swrve Unity SDK v. 4.10.1.
At the time we had the Crashlytics plugin by Fabric installed. But due to problems with too many field references in our classes (could not build Android because classes could not convert into dex format), we decided to remove Crashlytics from our Unity project.
This is when we got problems with Swrve.

On line 28 and 29 in SwrveButtonTriggerEvent.cs the strings "EventName" and "EventCategory" were declared as internal, which triggered a number of errors such as:
`Assets/Editor/Inspectors/SwrveButtonTriggerEventEditor.cs(24,72): error CS0122: SwrveIntegration.SwrveButtonTriggerEvent.EventCategory.get' is inaccessible due to its protection level`

I don't know how or why these errors are related to the removal of the Crashlytics plugin, but for some reason they appeared as a result of the removal of Crashlytics
.
We've temporarily done a workaround by changing the variable declaration to **public** instead of **internal**. From what we can tell, it seems to be running without any errors.

I would appreciate if someone could take a look at this and can tell if changing the variable scope could result in any unexpected effects.
Thanks!

**Comment by Sergio-Mira** [comment]
Hi @aaslun I can't find any reference to SwrveButtonTriggerEvent in our source code. It looks like it is part of your project and not our SDK.

**Comment by Sergio-Mira** [comment]
We've also seen the 'too many methods' problem before when including multiple versions of the same libraries, for example the support tools or the GCM/FCM libraries.

Changing the protection level of a field in your code should not have any effect on the final result after compilation.

**Comment by aaslun** [comment]
Thanks for the super fast response! I'm impressed! :)
Yes, you're most probably right, I did not realize that the code I was referring to was part of our project. Sorry about that.
But everything seems to be working now so I'm closing the issue.
Thanks again!
