### ISSUE TITLE
Could not build with Unity v,. 2017.1.1

### ISSUE THREAD

**Issue by aaslun** [Swrve/swrve-unity-sdk#143]
Hi again!
We had problems building our app on Unity 2017.1.1 with the latest release of Swrve SDK for Unity (4.10.1).
We solved it by changing the two platform conditional statements in SwrveNativeIOS.cs on line 11 and on line 287, from `#if UNITY_5` to `#if UNITY_2017_OR_NEWER`.

Hope this info can be of any use to you.
Thanks!

**Comment by Sergio-Mira** [comment]
Hi again @aaslun!

The upcoming release (4.11) will fix those. There is also an issue with Content-Length being written in the HTTP header which is no longer permitted in 2017.1 where you'll need to remove that line.
I'll update this issue when the new Unity SDK is out which will solve all the 2017.1 issues.

**Comment by adam-govan** [comment]
Hi aaslun, this should be addressed as part of our [release today](https://github.com/Swrve/swrve-unity-sdk/releases/tag/4.11)! Thank you so much for your patience and let us know if you run into any more issues! 😄
