### ISSUE TITLE
Cloud build issue with new rich push in SDK 4.11

### ISSUE THREAD

**Issue by daviddurston** [Swrve/swrve-unity-sdk#145]
Hi, our Unity cloud builds seem to be breaking now with the following error log:

`34436:        [xcode] Provisioning profile "YYY Internal" has app ID "com.xxx.yyy", which does not match the bundle ID "com.xxx.yyy.ServiceExtension".
34437:        [xcode] Provisioning profile "YYY Internal" doesn't match the entitlements file's value for the application-identifier entitlement.
34438:        [xcode] Warning: Multiple build commands for output file /BUILD_PATH/Library/Developer/Xcode/DerivedData/Unity-iPhone-hjyppnyzdjjzqranuzctrpgatksj/Build/Intermediates/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/SwrvePushExtension.appex/LICENSE
34439:        [xcode] Code signing is required for product type 'App Extension' in SDK 'iOS 10.3'
34440:        [xcode] ** ARCHIVE FAILED **
34441:        [xcode] The following build commands failed:
34442:        [xcode]     Check dependencies
34443:        [xcode] (1 failure)`

Please let me know if there's any other info I can try to get. Thanks.

**Comment by Sergio-Mira** [comment]
Hi @DavidDurston the latest SDK includes Rich Push which requires a Service Extension to work. For that Service Extension you'll need a separate provisioning profile created for "com.xxx.yyy.ServiceExtension" in your Apple Developer portal.

**Comment by daviddurston** [comment]
Ah, my mistake. I wonder if there should be a toggle for enabling this or not, so people don't get this error if they aren't using Swrve for pushes, or even just these rich pushes.

In case anyone else stumbles on this, here's the documentation related to Sergio's answer:
https://docs.swrve.com/developer-documentation/integration/ios/#Advanced_Push_Notifications

**Comment by Sergio-Mira** [comment]
We could check for appGroupIndentifier and not add the service extension if it is empty 👍

**Comment by daviddurston** [comment]
I'll go ahead and follow through with the instructions for now and close this ticket. Thanks for the help.
