### ISSUE TITLE
Specificed Cast not valid in new SwrveQaUser.cs Init()

### ISSUE THREAD

**Issue by thomasrs3** [Swrve/swrve-unity-sdk#146]
Update SwrveSDK to 7.20 from 7.0.2 for Unity 2019.4.15f1 has created a problem on game start.

InvalidCastException: Specified cast is not valid.
SwrveUnity.SwrveQaUser.Init (UnityEngine.MonoBehaviour container, System.String eventServer, System.String apiKey, System.Int32 appId, System.String userId, System.String appVersion, System.String deviceUUID, SwrveUnity.ISwrveStorage storage) (at Assets/Swrve/SwrveSDK/SwrveQaUser.cs:55)
SwrveSDK.Init (UnityEngine.MonoBehaviour container, System.Int32 appId, System.String apiKey, SwrveUnity.SwrveConfig config) (at Assets/Swrve/SwrveSDK/SwrveSDK.cs:224)
SwrveComponent.Init (System.Int32 appId, System.String apiKey, SwrveUnity.SwrveConfig config) (at Assets/Swrve/SwrveSDK/SwrveComponent.cs:95)
AnalyticSystem.InitializePlugin () (at Assets/Source/PluginIntegration/AnalyticSystem.cs:776)

Using 
`
Dictionary<string, object> qaUserDictionary = null;

qaUserDictionary = (Dictionary<string, object>)Json.Deserialize(instance.LoadQaUserFromCache());

SwrveQaUser.Update(qaUserDictionary);
`

as the cast to Dictionary is not valid on runtime. SwrveUnityMiniJSON doesn't seem to have a DeserializeObject function like using Newtonsoft.Json.

**Comment by Sergio-Mira** [comment]
Hi @thomasrs3 thanks for letting us know. We'll have a look and update this thread.

**Comment by Sergio-Mira** [comment]
Does that raise only on a device build? iOS? Android? On the Editor it seems to accept the cast

**Comment by Sergio-Mira** [comment]
Was able to reproduce on Unity 2019, Unity 2017 was giving a slightly different error. We are aiming to release a fix for this issue on a soon upcoming release.

**Comment by thomasrs3** [comment]
Yeah it is on Android and iOS when on play mode of 2019. Thanks for the response.

**Comment by Sergio-Mira** [comment]
Hi @thomasrs3 we've released a fix for that QA issue on 7.3.0. Will close this issue and can re-open if you still face it. Thanks again!
