### ISSUE TITLE
Firebase Exception from within SwrveMessageRenderer's DrawMessage() function

### ISSUE THREAD

**Issue by robertgioia** [Swrve/swrve-unity-sdk#147]
In Firebase, I see the following issue. It seems that one of the reference variables inside of DrawMessage() in the SwrveMessagingRenderer class is null at some point. 

```
Non-fatal Exception: java.lang.Exception
NullReferenceException : Object reference not set to an instance of an object.
SwrveUnity.Messaging.SwrveMessageRenderer.DrawMessage (SwrveUnity.Messaging.SwrveMessageRenderer)
SwrveSDK.OnGUI (SwrveSDK)
```

**Comment by davidbreenwex** [comment]
Hi @robertgioia,

Which version of the Swrve SDK are you currently using?
Also, Is it easily reproducible? Is it isolated to a specific campaign?

It may be easier to try to resolve this through our support portal. 
To open a ticket please email support@swrve.com. 

Thanks, 
David

**Comment by KevBrodigan** [comment]
Our latest release 8.0 had deprecated and removed SwrveMessagingRenderer class
