### ISSUE TITLE
"#error" in SwrveSDK.cs, Line 1019

### ISSUE THREAD

**Issue by johnny-tictoc** [Swrve/swrve-unity-sdk#90]
There is a "#error" in SwrveSDK.cs, Line 1019 that is causing an error on WebGL platform (Unity 5.3.4p1).

Is seems unnecessary. Removing it fixed the error for me.

**Comment by Sergio-Mira** [comment]
Thanks for letting us know! We unfortunately don't support the WebGL platform at the moment and there might be other problems that you could face when using the current SDK in the WebGL player.

**Comment by johnny-tictoc** [comment]
Has this been fixed? We are using Swrve on iOS and Android. I don't need to use it for WebGL. I just want it to not throw errors when I'm on that platform.

**Comment by Sergio-Mira** [comment]
Sorry @johnny-tictoc misunderstood the problem. We've removed that #error in the latest release 4.5 that came out today! Let us know how it goes and we can close this issue.

**Comment by johnny-tictoc** [comment]
@Sergio-Mira Thank you for resolving this quickly. It looks good.
